Qspring.application.name=payment-authorization-service
server.port=8080

external.api.anti-fraud.url=http://localhost:9090

cache.fraud-validation.ttl-minutes=5

resilience4j.circuitbreaker.instances.antiFraudService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.antiFraudService.sliding-window-size=6
resilience4j.circuitbreaker.instances.antiFraudService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.antiFraudService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.antiFraudService.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.antiFraudService.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.timelimiter.instances.antiFraudService.timeout-duration=2s
resilience4j.timelimiter.instances.antiFraudService.cancel-running-future=true

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operationsSorter=alpha

springdoc.swagger-ui.models-expand-depth=1

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cache.fraud-validation.ttl-minutes=5